#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_PROCESS 100
#define NUM_PROCESS 5
#define MAX_CPU_BURST_TIME 20
#define MAX_IO_BURST_TIME 5
#define MAX_TIME ((MAX_CPU_BURST_TIME) * (NUM_PROCESS))
#define TIME_QUANTUM 5

#endif